{
  "hash": "93fdb793fbc54e6f44fc741d20d5acaf",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"SIS: pairwise and reinfection counting\"\nsubtitle: \"NodeBasedModels.jl vignette N09: the SIS pairwise model, the reinfection-counting refinement with L = 0…4, and both against NetworkOutbreaks\"\n---\n\n## What this page shows\n\nIn SIS a recovered node is susceptible again (I → S, typing `:resus`). The model is outside the\nedge-based fragment T_EB (page E13), but the pairwise model accepts it. On a 3-regular network\nthe pairwise model reaches the right endemic level but gets the take-off wrong. Keeling, House,\nCooper and Pellis (2016, *PLoS Comput. Biol.* 12:e1005296) refine the pairwise model by counting infections: a node\nthat has been infected p times is kept in its own class S_p or I_p, up to a cap L. This page:\n\n1. builds the SIS pairwise model of `:sis_reg3` from a Catalyst network, then with the factory,\n   and asserts that the two are the same;\n2. applies the syntax transform `with_reinfection_counting(model, L)` for L = 0, …, 4 and lifts\n   each result, again in both forms;\n3. compares prevalence and cumulative incidence with the committed NetworkOutbreaks ensemble,\n   which is conditioned on survival;\n4. compares the fractions of nodes infected p times at the end of the run with the reinfection\n   histogram stored in the committed summary.\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nrequire_summaries([:sis_reg3])\n```\n:::\n\n\n\n## The SIS pairwise model, twice\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing Catalyst\nsis = @reaction_network sis begin\n    @parameters τ γ\n    τ, S + I --> 2I        # contact: per-contact (per-edge) rate τ\n    γ, I --> S             # recovery back into the susceptible class (type resus)\nend\nmodel = contact_model(sis)          # the typing report: T_net, not T_EB\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nContactModel :sis  (source: Catalyst.ReactionSystem; method: stoichiometry; rates: PerContact)\n  species       S (Sus)   I\n  contacts      [1] S + I → I + I    τ    contact    infector I, entry I\n  transitions   [2] I → S            γ    resus\n  typing        T_net  ⇒  edge_based ✗  s_anchored ✗  pairwise ✓  individual ✓  pair ✓  stochastic ✓  mass_action ✓\n  violations    `γ, I --> S` (type resus: node → sus) produces the susceptible species S.\n  assumptions   Sus inferred as recipients \\ contact products = {S}\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsc = scenario(:sis_reg3)            # 3-regular, τ = 1/2, γ = 1/4, 1% seeds in I, t ∈ [0, 80]\n@assert isequivalent(model, sc.model)\nsys  = node_based(model, sc.network)                                                           # low level\nsysF = generate_pairwise(sis_model(), sc.network, default_closure(sc.network); cumulative = true)  # factory\n@assert vector_fields_equal(symbolic_ode(sys), symbolic_ode(sysF))\n(; closure = default_closure(sc.network), K = closure_constant(sc.network.degrees))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(closure = BernoulliClosure(), K = 0.6666666666666666)\n```\n:::\n:::\n\n\n\nOn a k-regular network the default closure is the Bernoulli (Keeling) closure\n[ABC] ≈ K[AB][BC]/[B] with K = (k − 1)/k. The equations, with the pairs counted as ordered pairs\n([SS] counts each SS edge twice):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsymbolic_ode(sys)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nSymbolicODE :pairwise_sis (6 states)\n  dS/dt = I(t)*γ - SI(t)*τ\n  dI/dt = -I(t)*γ + SI(t)*τ\n  dSS/dt = 2SI(t)*γ - 1.3333333333333333ifelse(S(t) == 0, 0, (SI(t)*SS(t)) / S(t))*τ\n  dSI/dt = II(t)*γ - SI(t)*γ - SI(t)*τ + 0.6666666666666666ifelse(S(t) == 0, 0, (SI(t)*SS(t)) / S(t))*τ - 0.6666666666666666ifelse(S(t) == 0, 0, (SI(t)^2) / S(t))*τ\n  dII/dt = -2II(t)*γ + 2SI(t)*τ + 1.3333333333333333ifelse(S(t) == 0, 0, (SI(t)^2) / S(t))*τ\n  dcumulative/dt = SI(t)*τ\n  parameters  γ, τ\n```\n:::\n:::\n\n\n\nThe scenario is above the pairwise threshold τ_c = γ/(k − 1):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\na = anchors(sc);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n:sis_reg3: γ = 0.25, τ = 0.5; seeds I 0.01; t = 0:0.25:80; edge-based R₀ not defined (model outside T_EB); pairwise threshold τ_c = 0.125, τ/τ_c = 4 (differs from the canonical anchors: no edge-based R₀, τ ≠ 1/6)\n```\n:::\n:::\n\n\n\nHere τ/τ_c = 4, so the pairwise model has an endemic\nequilibrium.\n\n## Reinfection counting as a syntax transform\n\n`with_reinfection_counting(model, L)` refines every compartment X into X_p, where p is the\nnumber of infections the node has had, saturating at L. An infection takes S_p to I_{min(p+1, L)}\nwhatever the count of the infector; every other reaction keeps the count. For L = 2:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm2 = with_reinfection_counting(model, 2)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nContactModel :sis_reinf_L2  (source: transform; method: explicit; rates: PerContact)\n  species       S_0 (Sus)   S_1 (Sus)   S_2 (Sus)   I_1   I_2\n  contacts      [1] S_0 + I_1 → I_1 + I_1    τ    contact    infector I_1, entry I_1\n                [2] S_0 + I_2 → I_1 + I_2    τ    contact    infector I_2, entry I_1\n                [3] S_1 + I_1 → I_2 + I_1    τ    contact    infector I_1, entry I_2\n                [4] S_1 + I_2 → I_2 + I_2    τ    contact    infector I_2, entry I_2\n                [5] S_2 + I_1 → I_2 + I_1    τ    contact    infector I_1, entry I_2\n                [6] S_2 + I_2 → I_2 + I_2    τ    contact    infector I_2, entry I_2\n  transitions   [7] I_1 → S_1                γ    resus\n                [8] I_2 → S_2                γ    resus\n  typing        T_net  ⇒  edge_based ✗  s_anchored ✗  pairwise ✓  individual ✓  pair ✓  stochastic ✓  mass_action ✓\n  violations    `γ, I_1 --> S_1` (type resus: node → sus) produces the susceptible species S_1.\n                `γ, I_2 --> S_2` (type resus: node → sus) produces the susceptible species S_2.\n                `τ, S_1 + I_1 --> I_2 + I_1`: S_1 is a second susceptible class (multiple_sus).\n                `τ, S_2 + I_1 --> I_2 + I_1`: S_2 is a third susceptible class (multiple_sus).\n  assumptions   Sus inferred as recipients \\ contact products = {S}\n                transform of a catalyst model (method stoichiometry)\n                with_reinfection_counting(L = 2): X ↦ X_p by infection count p ≤ 2 (saturating); infections: S_I_to_I\n```\n:::\n:::\n\n\n\n``` {.julia .cell-code}\nmd_table([\"reaction\", \"type\", \"from\", \"to\", \"rate\"],\n         vcat([(string(c.name), \"contact\", \"$(c.recipient) + $(c.infector)\", \"$(c.product) + $(c.infector)\",\n                string(c.rate)) for c in contacts(m2)],\n              [(string(t.name), \"transition\", string(t.from), string(t.to), string(t.rate))\n               for t in m2.transitions]))\n```\n| reaction | type | from | to | rate |\n|---|---|---|---|---|\n| S_0_I_1_to_I_1 | contact | S_0 + I_1 | I_1 + I_1 | τ |\n| S_0_I_2_to_I_1 | contact | S_0 + I_2 | I_1 + I_2 | τ |\n| S_1_I_1_to_I_2 | contact | S_1 + I_1 | I_2 + I_1 | τ |\n| S_1_I_2_to_I_2 | contact | S_1 + I_2 | I_2 + I_2 | τ |\n| S_2_I_1_to_I_2 | contact | S_2 + I_1 | I_2 + I_1 | τ |\n| S_2_I_2_to_I_2 | contact | S_2 + I_2 | I_2 + I_2 | τ |\n| I_1_to_S_1 | transition | I_1 | S_1 | γ |\n| I_2_to_S_2 | transition | I_2 | S_2 | γ |\n\n\n\n\nThe refined model has three susceptible classes S₀, S₁ and S₂ and arrows back into two of them,\nso it is again a T_net model for the node-based and stochastic back ends only. Nodes that have\nnever been infected start in S₀. The seeds are counted as infected once, so they start in I₁, as\nin NetworkOutbreaks, whose reinfection counter also counts a seed once. The seeding is therefore\nthe scenario's 1% placed in the count-one class:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nρ = last(only(sc.initial.fractions))\nseed(L) = SeedFraction(Symbol(:I_, min(1, L)) => ρ)       # L = 0: the unrefined model, I₀ = I\n(; ρ, seeds = [seed(L) for L in 0:4])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(ρ = 0.01, seeds = SeedFraction[SeedFraction([:I_0 => 0.01], nothing), SeedFraction([:I_1 => 0.01], nothing), SeedFraction([:I_1 => 0.01], nothing), SeedFraction([:I_1 => 0.01], nothing), SeedFraction([:I_1 => 0.01], nothing)])\n```\n:::\n:::\n\n\n\nEach refined model is lifted in both forms, and the two vector fields are compared:\n\n``` {.julia .cell-code}\nLs = 0:4\nrefined = Dict(L => with_reinfection_counting(model, L) for L in Ls)\npw = Dict(L => node_based(refined[L], sc.network) for L in Ls)\nrows = map(Ls) do L\n    f = generate_pairwise(with_reinfection_counting(sis_model(), L), sc.network, BernoulliClosure(); cumulative = true)\n    (L, length(pw[L].singles), length(pw[L].pairs), vector_fields_equal(symbolic_ode(pw[L]), symbolic_ode(f)))\nend\nmd_table([\"L\", \"singles\", \"pairs\", \"node_based = generate_pairwise\"], rows)\n```\n| L | singles | pairs | node_based = generate_pairwise |\n|---:|---:|---:|---:|\n| 0 | 2 | 3 | true |\n| 1 | 3 | 6 | true |\n| 2 | 5 | 15 | true |\n| 3 | 7 | 28 | true |\n| 4 | 9 | 45 | true |\n\n\n\n\nFor L = 1 the system is small enough to read. S₀ holds the nodes that have never been infected\nand S₁ those that have recovered at least once:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsymbolic_ode(pw[1])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nSymbolicODE :pairwise_sis_reinf_L1 (10 states)\n  dS_0/dt = -S_0I_1(t)*τ\n  dS_1/dt = I_1(t)*γ - S_1I_1(t)*τ\n  dI_1/dt = -I_1(t)*γ + S_0I_1(t)*τ + S_1I_1(t)*τ\n  dS_0S_0/dt = -1.3333333333333333ifelse(S_0(t) == 0, 0, (S_0I_1(t)*S_0S_0(t)) / S_0(t))*τ\n  dS_0S_1/dt = S_0I_1(t)*γ - 0.6666666666666666(ifelse(S_0(t) == 0, 0, (S_0I_1(t)*S_0S_1(t)) / S_0(t)) + ifelse(S_1(t) == 0, 0, (S_0S_1(t)*S_1I_1(t)) / S_1(t)))*τ\n  dS_0I_1/dt = -S_0I_1(t)*(γ + τ) + 0.6666666666666666ifelse(S_0(t) == 0, 0, (S_0I_1(t)*S_0S_0(t)) / S_0(t))*τ + 0.6666666666666666ifelse(S_1(t) == 0, 0, (S_0S_1(t)*S_1I_1(t)) / S_1(t))*τ - 0.6666666666666666ifelse(S_0(t) == 0, 0, (S_0I_1(t)^2) / S_0(t))*τ\n  dS_1S_1/dt = 2S_1I_1(t)*γ - 1.3333333333333333ifelse(S_1(t) == 0, 0, (S_1I_1(t)*S_1S_1(t)) / S_1(t))*τ\n  dS_1I_1/dt = I_1I_1(t)*γ - S_1I_1(t)*(γ + τ) - 0.6666666666666666ifelse(S_1(t) == 0, 0, (S_1I_1(t)^2) / S_1(t))*τ + 0.6666666666666666(ifelse(S_0(t) == 0, 0, (S_0I_1(t)*S_0S_1(t)) / S_0(t)) + ifelse(S_1(t) == 0, 0, (S_1I_1(t)*S_1S_1(t)) / S_1(t)))*τ\n  dI_1I_1/dt = -2I_1I_1(t)*γ + 2S_0I_1(t)*τ + 2S_1I_1(t)*τ + 1.3333333333333333ifelse(S_0(t) == 0, 0, (S_0I_1(t)^2) / S_0(t))*τ + 1.3333333333333333ifelse(S_1(t) == 0, 0, (S_1I_1(t)^2) / S_1(t))*τ\n  dcumulative/dt = S_0I_1(t)*τ + S_1I_1(t)*τ\n  parameters  γ, τ\n```\n:::\n:::\n\n\n\nThe closure acts on the refined pairs, for example [S₀ S₀ I₁] ≈ K[S₀S₀][S₀I₁]/[S₀]. Summed over\np, the refined singles are not the solution of the unrefined pairwise model, because the triples\nare closed at the refined level. The refinement therefore changes the prevalence curve, as the\ncomparison below shows.\n\n## Against simulation\n\nThe pairwise systems are solved on the scenario grid. The refined models are labelled with the\nrepresentation `:reinfection`, so that the plots give each L its own colour; L = 0 keeps the\npairwise style. Their prevalence is the sum over counts,\nI = Σ_p I_p (`reinfection_totals`), and their `:cumulative` accumulator counts the seeds and every\ninfection, reinfections included. NetworkOutbreaks' `:cumulative` observable counts the same\nevents, so for SIS it is the mean number of infections per node (it exceeds 1).\n\nThe systems are integrated with the explicit Runge–Kutta method Tsit5 at the package's default\ntolerances (reltol 10⁻⁸, abstol 10⁻¹⁰); the numerical caveat below says why the default\nauto-switching solver is not used here.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing OrdinaryDiffEqDefault: Tsit5\nsols = Dict(L => solve_epidemic(pw[L], sc; initial = seed(L), solver = Tsit5()) for L in Ls)\nfunction lumped_curves(L)\n    tot = reinfection_totals(pw[L], sols[L])\n    cum = model_curves(pw[L], sols[L]; t = sc.tgrid)[:cumulative]\n    ModelCurves(sc.tgrid, Dict(:I => tot[:I], :S => tot[:S], :cumulative => cum);\n                label = \"pairwise, L = $(L)\", representation = L == 0 ? :pairwise : :reinfection)\nend\ndets = [lumped_curves(L) for L in Ls]\nref = scenario_summary(sc)\ntab = compare(ref, dets; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sis_reg3  (scenario 485d890e; conditioned mean of 200 runs)\n  curve            observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  pairwise, L = 0  I            0.14556      9.50   0.00160     93.69  14.70400  [14.70400, 14.70400]  -0.00023      5.00     0.153\n  pairwise, L = 0  cumulative   0.27836     10.75   0.00362     79.82  14.70400  [14.70400, 14.70400]   0.23805      0.00     0.025\n  pairwise, L = 1  I            0.00289     14.25   0.00160      6.71  14.48108  [14.48108, 14.48108]  -0.00023      8.75     0.287\n  pairwise, L = 1  cumulative   0.01559     78.25   0.00362      4.32  14.48108  [14.48108, 14.48108]   0.01513      0.00     0.408\n  pairwise, L = 2  I            0.00382      9.75   0.00160      5.33  14.47579  [14.47579, 14.47579]  -0.00023     41.00     0.243\n  pairwise, L = 2  cumulative   0.01031     78.25   0.00362      2.85  14.47579  [14.47579, 14.47579]   0.00984      0.00     0.667\n  pairwise, L = 3  I            0.00392      9.75   0.00160      5.29  14.47558  [14.47558, 14.47558]  -0.00023     43.00     0.246\n  pairwise, L = 3  cumulative   0.01009     78.25   0.00362      2.79  14.47558  [14.47558, 14.47558]   0.00962      0.00     0.698\n  pairwise, L = 4  I            0.00393      9.75   0.00160      5.28  14.47555  [14.47555, 14.47555]  -0.00023     43.00     0.246\n  pairwise, L = 4  cumulative   0.01007     78.25   0.00362      2.79  14.47555  [14.47555, 14.47555]   0.00960      0.00     0.698\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndescribe_reference(ref);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNetworkOutbreaks reference :sis_reg3 (hash 485d890e): N = 10000 nodes, 200 runs on a fresh graph per run, algorithm :next_reaction; conditioning: surviving runs only (prevalence at t_end > 0); 200 of 200 runs kept (surviving runs), P(survival) = 1.000 (95% CI 0.981–1.000); no time alignment.\n```\n:::\n:::\n\n\n\n::: {.cell fig-height='6' execution_count=1}\n``` {.julia .cell-code}\ndistinct_styles!(comparisonplot(ref, dets...; observables = [:I, :cumulative]))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Pairwise SIS models with reinfection counting (L = 0 is the plain pairwise model) against the committed NetworkOutbreaks ensemble of `:sis_reg3`, conditioned on survival (spread band q2.5–q97.5 of the runs; residual panel: mean band ±1.96 SE).](index_files/figure-pdf/cell-14-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\nThe table above is `compare` over the whole time course. Its ΔR∞ column is not a comparison of\nlike with like for SIS. `compare` defines ΔR∞ as the model's `:cumulative` at t = 80 minus the\nmean of the ensemble's per-run final size, and for SIS that final size is the fraction of nodes\n*ever* infected:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfs = ref.final_size[ref.major]\n(; mean_fraction_ever_infected = sum(fs) / length(fs),\n   pairwise_cumulative_80 = dets[1][:cumulative][end],\n   ΔR∞_pairwise = tab[dets[1].label, :cumulative].ΔR∞)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(mean_fraction_ever_infected = 1.0, pairwise_cumulative_80 = 15.704003220875496, ΔR∞_pairwise = 14.704003220875496)\n```\n:::\n:::\n\n\n\nThe model's `:cumulative` counts every infection, reinfections included, so ΔR∞ is the mean number\nof infections per node minus the fraction ever infected, and it is large for every L. The like\nfor like comparison of `:cumulative` is the `cumulative(80) − NO` column below, against the\nsimulated mean of `:cumulative`. The comparisonplot's peak statistics are not meaningful on an\nendemic plateau either. The quantities that matter are the largest gap and the endemic level:\n\n``` {.julia .cell-code}\nst, sc_cum = ref.cond[:I], ref.cond[:cumulative]\nmd_table([\"model\", \"D∞(I)\", \"t at D∞(I)\", \"I(80)\", \"I(80) − NO\", \"cumulative(80)\", \"cumulative(80) − NO\"],\n         vcat([(c.label, tab[c.label, :I].D∞, tab[c.label, :I].t_D∞, c[:I][end], c[:I][end] - st.mean[end],\n                c[:cumulative][end], c[:cumulative][end] - sc_cum.mean[end]) for c in dets],\n              [(\"NetworkOutbreaks (mean ± SE)\", NaN, NaN, st.mean[end], st.se[end], sc_cum.mean[end], sc_cum.se[end])]))\n```\n| model | D∞(I) | t at D∞(I) | I(80) | I(80) − NO | cumulative(80) | cumulative(80) − NO |\n|---|---:|---:|---:|---:|---:|---:|\n| pairwise, L = 0 | 0.1456 | 9.5 | 0.8182 | 0.001126 | 15.7 | 0.2381 |\n| pairwise, L = 1 | 0.002891 | 14.25 | 0.8182 | 0.001126 | 15.48 | 0.01513 |\n| pairwise, L = 2 | 0.003824 | 9.75 | 0.8182 | 0.001126 | 15.48 | 0.00984 |\n| pairwise, L = 3 | 0.003921 | 9.75 | 0.8182 | 0.001126 | 15.48 | 0.009624 |\n| pairwise, L = 4 | 0.003925 | 9.75 | 0.8182 | 0.001126 | 15.48 | 0.009599 |\n| NetworkOutbreaks (mean ± SE) | NaN | NaN | 0.8171 | 0.0003 | 15.47 | 0.003598 |\n\n\n\n\n\n\n\nThe plain pairwise model (L = 0) misses the take-off by up to D∞(I) = 0\\.1456.\nCounting a single infection (L = 1) brings this to 0\\.002891, and L = 2, 3, 4 give\n0\\.003824, 0\\.003921, 0\\.003925. The lumped L = 1 prevalence differs from the plain pairwise\nprevalence by up to 0\\.1464, which is the effect of closing the triples at the\nrefined level. The first refinement does almost all the work. It separates the nodes that have\nnever been infected, whose neighbourhoods are still close to those of an SIR epidemic, from the\nnodes that have recovered next to an infected neighbour. The endemic levels at t = 80 are the same for every L, 0\\.8182: the refinement\nchanges the approach to the endemic equilibrium, not the equilibrium. They are\n0\\.001126 above the simulated level, which is\n3\\.753 standard errors of the simulated mean: a small\nbias of the pairwise closure at equilibrium. Counting infections also corrects most of the\nplain pairwise model's excess in the mean number of infections per node (the `cumulative(80)`\ncolumn).\n\nThe early phase, where the models differ:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\np = plot(ref, :I; median = false, legend = :bottomright, xlabel = \"t\", ylabel = \"I (fraction of nodes)\",\n         title = \"SIS on a 3-regular network: take-off\")\nfor c in dets\n    plot!(p, c, :I)\nend\ndistinct_styles!(p)\nxlims!(p, 0, 30)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![The first 30 time units of the figure above (prevalence; band: spread q2.5–q97.5 of the surviving runs).](index_files/figure-pdf/cell-18-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n### A numerical caveat\n\nWith the default solver of `solve_epidemic` (an automatic switch between non-stiff and stiff\nmethods), for L = 4, the prevalence agrees with the Tsit5 solution but the `:cumulative`\naccumulator does not. The check integrates the accumulator's own\nright-hand side, τ Σ_{p,q}[S_p I_q], by the trapezoidal rule on the saved Tsit5 solution:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndefault4 = solve_epidemic(pw[4], sc; initial = seed(4))\nisSI(X, Y) = Set(base_compartment_of(refined[4], Z) for Z in (X, Y)) == Set([:S, :I])\nSIpairs = [v for ((X, Y), v) in pw[4].pairs if isSI(X, Y)]\ncumrate(sol) = [sc.params[:τ] * sum(sol[v][j] for v in SIpairs) for j in eachindex(sol.t)]\nr4 = cumrate(sols[4]); dt = step(sc.tgrid)\nquadrature = ρ + sum((r4[1:end-1] .+ r4[2:end]) ./ 2) * dt\n(; tsit5 = dets[5][:cumulative][end], default_solver = model_curves(pw[4], default4; t = sc.tgrid)[:cumulative][end],\n   trapezoid_on_tsit5 = quadrature,\n   max_prevalence_gap = maximum(abs.(reinfection_totals(pw[4], default4)[:I] .- dets[5][:I])))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(tsit5 = 15.475551085249329, default_solver = 15.318376250741608, trapezoid_on_tsit5 = 15.475533100027446, max_prevalence_gap = 1.1356475759782825e-9)\n```\n:::\n:::\n\n\n\nThe Tsit5 value agrees with the quadrature to within the trapezoidal error of the 0.25 grid,\nand the default solver's value does not. This is a defect of the default solver path for this\nsystem, reported to the package owners; the page does not depend on it.\n\n## Reinfection histograms\n\nThe committed summary stores, for the end of the run (t = 80), the mean fraction of nodes that\nhave been infected p times, over the surviving runs:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nh = ref.extras[:reinfection_histogram][\"cond\"]\n(; t_end = last(sc.tgrid), buckets = length(h), total = sum(h), mode = argmax(h) - 1,\n   mean_infections = sum((p - 1) * h[p] for p in eachindex(h)), cumulative_mean = sc_cum.mean[end])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(t_end = 80.0, buckets = 35, total = 1.0, mode = 15, mean_infections = 15.465947000000002, cumulative_mean = 15.465952)\n```\n:::\n:::\n\n\n\nThe mean of the histogram is the simulated `:cumulative` at t = 80, as it should be. By t = 80 the\ntypical node has been infected 15 times:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nbar(0:length(h)-1, h; xlabel = \"number of infections p\", ylabel = \"fraction of nodes\", label = \"NetworkOutbreaks\",\n    title = \"Reinfection histogram of :sis_reg3 at t = 80\", legend = :topright)\nvline!([1, 2, 3, 4]; linestyle = :dash, color = :gray, label = \"caps L = 1…4\")\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Fraction of nodes infected p times by t = 80 (NetworkOutbreaks, mean over the surviving runs), and where the caps L = 1, …, 4 of the pairwise models fall.](index_files/figure-pdf/cell-21-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\nA model with cap L puts every node infected L or more times into the top class, so the right\ncomparison is with the simulated histogram saturated at L. The model's fraction infected p times\nis [S_p] + [I_p]:\n\n``` {.julia .cell-code}\nmodel_hist(L) = [sols[L][pw[L].singles[Symbol(:S_, q)]][end] +\n                 (haskey(pw[L].singles, Symbol(:I_, q)) ? sols[L][pw[L].singles[Symbol(:I_, q)]][end] : 0.0)\n                 for q in 0:L]\nsaturated(L) = [q < L ? h[q+1] : sum(h[L+1:end]) for q in 0:L]\nrows = [(L, q, model_hist(L)[q+1], saturated(L)[q+1]) for L in 1:4 for q in 0:L]\nmd_table([\"L\", \"p (top class: p ≥ L)\", \"pairwise fraction\", \"NetworkOutbreaks fraction\"], rows)\n```\n| L | p (top class: p ≥ L) | pairwise fraction | NetworkOutbreaks fraction |\n|---:|---:|---:|---:|\n| 1 | 0 | 1.365e-23 | 0 |\n| 1 | 1 | 1 | 1 |\n| 2 | 0 | 6.126e-28 | 0 |\n| 2 | 1 | 2.969e-08 | 0 |\n| 2 | 2 | 1 | 1 |\n| 3 | 0 | 5.238e-29 | 0 |\n| 3 | 1 | 2.97e-08 | 0 |\n| 3 | 2 | 6.504e-07 | 0 |\n| 3 | 3 | 1 | 1 |\n| 4 | 0 | 4.31e-29 | 0 |\n| 4 | 1 | 2.97e-08 | 0 |\n| 4 | 2 | 6.504e-07 | 0 |\n| 4 | 3 | 6.894e-06 | 1e-05 |\n| 4 | 4 | 1 | 1 |\n\n\n\n\n\n\n\nWith L ≤ 4 this comparison can only test the lowest buckets. Almost every node has been infected\nat least four times, and the fraction infected exactly three times is\n6\\.894e\\-06 in the L = 4 model and 1e\\-05 in the simulation. The\nsmallest nonzero fraction the ensemble can resolve is 1/(N · runs) = 5e\\-07.\nThe mean of the whole histogram is compared through `:cumulative` in the table above.\n\n## Summary\n\n``` {.julia .cell-code}\nmd_table([\"quantity\", \"value\"],\n         [(\"pairwise threshold τ_c (τ/τ_c)\", \"$(fmt(a.τc)) ($(fmt(sc.params[:τ] / a.τc)))\"),\n          (\"D∞(I), plain pairwise (L = 0)\", D[1]),\n          (\"D∞(I), reinfection counting L = 1 / 4\", \"$(fmt(D[2])) / $(fmt(D[5]))\"),\n          (\"simulated I(80) ± SE\", \"$(fmt(st.mean[end])) ± $(fmt(st.se[end]))\"),\n          (\"simulated mean number of infections per node at t = 80\", sc_cum.mean[end]),\n          (\"pairwise L = 0 / L = 4 cumulative(80)\", \"$(fmt(dets[1][:cumulative][end])) / $(fmt(dets[5][:cumulative][end]))\")])\n```\n| quantity | value |\n|---|---|\n| pairwise threshold τ_c (τ/τ_c) | 0.125 (4) |\n| D∞(I), plain pairwise (L = 0) | 0.1456 |\n| D∞(I), reinfection counting L = 1 / 4 | 0.002891 / 0.003925 |\n| simulated I(80) ± SE | 0.8171 ± 0.0003 |\n| simulated mean number of infections per node at t = 80 | 15.47 |\n| pairwise L = 0 / L = 4 cumulative(80) | 15.7 / 15.48 |\n\n\n\n\nNo Lean statement is involved on this page. Page [N12](../N12_sis_comparison/index.qmd) puts the\nreinfection-counting models next to the motif and neighbourhood approximations.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-pdf"
    ],
    "filters": [],
    "includes": {}
  }
}