"""
Cross-validate NodeBasedModels.jl against EoN (Python) reference values.
Reference data generated by eon_crossval.py using EoN 1.2.

All scenarios use canonical R₀=2, γ=0.25 on k=6 regular graphs (N=1000).
Graph seed=42 matches the EoN reference (networkx.random_regular_graph(6,1000,seed=42)).
"""

using Test
using JSON3
using NodeBasedModels
using Graphs
using Random

const ref = JSON3.read(read(joinpath(@__DIR__, "eon_reference.json"), String))

@testset "EoN cross-validation" begin
    Random.seed!(42)
    G = random_regular_graph(1000, 6)
    net = GraphNetwork(G)
    τ = 1/6    # R₀ = (k-1)T = 5*0.4 = 2
    γ = 0.25

    @testset "SIR individual-based (NIMFA) on k=6 regular" begin
        ib = generate_individual_based(sir_model(), net;
            infection_rate = τ, recovery_rate = γ,
            tspan = (0.0, 40.0), saveat = 0.2, ε = 0.01)
        I_ib = aggregate(ib, :I) ./ 1000
        @test isapprox(maximum(I_ib), ref.sir_ib_regular6.peak_I; rtol=0.02)
    end

    @testset "SIR pair-based (Kirkwood) on k=6 regular" begin
        pb = generate_pair_based(sir_model(), net;
            infection_rate = τ, recovery_rate = γ,
            tspan = (0.0, 40.0), saveat = 0.2, ε = 0.01)
        I_pb = aggregate(pb, :I) ./ 1000
        @test isapprox(maximum(I_pb), ref.sir_pb_regular6.peak_I; rtol=0.02)
    end

    @testset "SIR homogeneous pairwise (population) on k=6" begin
        psys = generate_pairwise(sir_model(), regular_network(6),
            BernoulliClosure(); tspan = (0.0, 40.0), N = 1.0,
            seed_fraction = 0.01)
        p = copy(psys.params); p[:τ] = τ; p[:γ] = γ
        sol = solve_pairwise(psys, p; reltol=1e-8, abstol=1e-10)
        I_pw = sol[psys.singles[:I]]
        @test isapprox(maximum(I_pw), ref.sir_hom_pairwise_k6.peak_I; rtol=0.02)
    end
end
