{
  "hash": "aa37f8c912cf924b7df3a0b876b53a48",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"Neighbourhood model (n = 2)\"\nsubtitle: \"NodeBasedModels.jl vignette N11: SIS by the number of infected neighbours of each node, on a 3-regular network, against NetworkOutbreaks\"\n---\n\n## What this page shows\n\nThe neighbourhood model [Keeling, House, Cooper and Pellis 2016, *PLoS Comput. Biol.*\n12:e1005296, approximation 3; compare the neighbourhood configuration model of\n@hadjichrysanthou2012] classifies every node of a k-regular network by its own state and the\nnumber y of its k neighbours that are infected: [S_y] and [I_y], y = 0, …, k. A node's own\nevents are exact in these variables. The events of its neighbours need a closure, which at\norder n = 2 uses the states of pairs. This page:\n\n1. builds the model from the Catalyst SIS model of `:sis_reg3` and with the direct constructor,\n   and checks that the two are the same system;\n2. writes out the equations and checks the numeric right-hand side against the independent\n   symbolic builder;\n3. checks the conservation laws along a solution;\n4. compares the prevalence with the committed NetworkOutbreaks ensemble and with the pairwise\n   model.\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nrequire_summaries([:sis_reg3])\n```\n:::\n\n\n\n## The model, twice\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing Catalyst, StableRNGs\nsis = @reaction_network sis begin\n    @parameters τ γ\n    τ, S + I --> 2I        # contact: per-contact (per-edge) rate τ\n    γ, I --> S             # recovery back into the susceptible class\nend\nmodel = contact_model(sis)\nsc = scenario(:sis_reg3)            # 3-regular, τ = 1/2, γ = 1/4, 1% seeds in I, t ∈ [0, 80]\n@assert isequivalent(model, sc.model)\nρ = last(only(sc.initial.fractions))\nk = 3\nnb  = node_based(model, sc.network; level = :neighbourhood, n = 2, p = sc.params,\n                 initial = sc.initial, tspan = sc.tspan)                                      # low level\nnbD = generate_neighbourhood(CompartmentalModel(model), k, 2; β = sc.params[:τ], γ = sc.params[:γ],\n                             tspan = sc.tspan, ε = ρ)                                         # direct constructor\nfunction max_rhs_gap(a, rhs_b; n = 25, seed = 1)\n    rng = StableRNG(seed)\n    d1, d2 = similar(a.u0), similar(a.u0)\n    gap = 0.0\n    for _ in 1:n\n        u = a.u0 .* (0.2 .+ 1.6 .* rand(rng, length(a.u0))) .+ 1e-3 .* rand(rng, length(a.u0))\n        a.rhs!(d1, u, a.params, 0.0)\n        rhs_b(d2, u)\n        gap = max(gap, maximum(abs.(d1 .- d2)))\n    end\n    return gap\nend\n(; variables = nb.var_names, u0_equal = nb.u0 == nbD.u0,\n   max_rhs_gap = max_rhs_gap(nb, (du, u) -> nbD.rhs!(du, u, nbD.params, 0.0)))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(variables = [:S_0, :S_1, :S_2, :S_3, :I_0, :I_1, :I_2, :I_3], u0_equal = true, max_rhs_gap = 0.0)\n```\n:::\n:::\n\n\n\nThe initial condition is random mixing: a fraction ρ = 0\\.01 of the nodes is\ninfected independently, so the number of infected neighbours is Binomial(k, ρ) for every node.\n\n## The equations\n\nWith per-contact rate τ and recovery rate γ, a node in [S_y] is infected at rate τy and a node\nin [I_y] recovers at rate γ. These events are the node's own and need no closure. A neighbour of\nthe node recovers at rate γ, which moves the node from y to y − 1. A susceptible neighbour of the\nnode is infected at a rate that depends on that neighbour's other neighbours. The n = 2 closure\nreplaces it by its average over the pairs of the same type:\n\n$$\n\\omega_S = \\tau\\,\\frac{\\sum_y y\\,(k-y)\\,[S_y]}{\\sum_y (k-y)\\,[S_y]}, \\qquad\n\\omega_I = \\tau\\,\\frac{\\sum_y y^2\\,[S_y]}{\\sum_y y\\,[S_y]}.\n$$\n\nHere ω_S is for a susceptible neighbour of an S node and ω_I for a susceptible neighbour of an I\nnode. The model is\n\n$$\n\\begin{aligned}\n\\frac{d[S_y]}{dt} &= \\gamma [I_y] - \\tau y [S_y] + \\gamma\\big((y+1)[S_{y+1}] - y[S_y]\\big)\n  + \\omega_S\\big((k-y+1)[S_{y-1}] - (k-y)[S_y]\\big),\\\\\n\\frac{d[I_y]}{dt} &= \\tau y [S_y] - \\gamma [I_y] + \\gamma\\big((y+1)[I_{y+1}] - y[I_y]\\big)\n  + \\omega_I\\big((k-y+1)[I_{y-1}] - (k-y)[I_y]\\big),\n\\end{aligned}\n$$\n\nwith [S_{−1}] = [S_{k+1}] = 0 and the same for I. `build_neighbourhood_symbolic_rhs(k)` writes\nthese equations with Symbolics from the paper's equations, without calling the numeric builder.\nFor k = 3, with the variables renamed:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrhs_sym!, keys_sym, exprs = build_neighbourhood_symbolic_rhs(k)\n@assert [Symbol(X, :_, y) for (X, y) in keys_sym] == nb.var_names\npretty = Dict{Any,Any}(Symbolics.variable(Symbol(\"u_\", i)) => Symbolics.variable(nb.var_names[i]) for i in eachindex(nb.var_names))\npretty[Symbolics.variable(:β_sym)] = Symbolics.variable(:τ)       # the builder names the per-contact rate β\npretty[Symbolics.variable(:γ_sym)] = Symbolics.variable(:γ)\nfor (i, e) in enumerate(exprs)\n    println(\"d\", nb.var_names[i], \"/dt = \", Symbolics.substitute(e, pretty))\nend\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndS_0/dt = I_0*γ + S_1*γ - 3S_0*ifelse((3S_0 + 2S_1 + S_2) < 1.0e-12, 0, (2S_1 + 2S_2) / (3S_0 + 2S_1 + S_2))*τ\ndS_1/dt = I_1*γ + (-S_1 + 2S_2)*γ - S_1*τ + (3S_0 - 2S_1)*ifelse((3S_0 + 2S_1 + S_2) < 1.0e-12, 0, (2S_1 + 2S_2) / (3S_0 + 2S_1 + S_2))*τ\ndS_2/dt = I_2*γ + (-2S_2 + 3S_3)*γ - 2S_2*τ + (2S_1 - S_2)*ifelse((3S_0 + 2S_1 + S_2) < 1.0e-12, 0, (2S_1 + 2S_2) / (3S_0 + 2S_1 + S_2))*τ\ndS_3/dt = I_3*γ - 3S_3*γ - 3S_3*τ + S_2*ifelse((3S_0 + 2S_1 + S_2) < 1.0e-12, 0, (2S_1 + 2S_2) / (3S_0 + 2S_1 + S_2))*τ\ndI_0/dt = -I_0*γ + I_1*γ - 3I_0*ifelse((S_1 + 2S_2 + 3S_3) < 1.0e-12, 0, (S_1 + 4S_2 + 9S_3) / (S_1 + 2S_2 + 3S_3))*τ\ndI_1/dt = (-I_1 + 2I_2)*γ - I_1*γ + S_1*τ + (3I_0 - 2I_1)*ifelse((S_1 + 2S_2 + 3S_3) < 1.0e-12, 0, (S_1 + 4S_2 + 9S_3) / (S_1 + 2S_2 + 3S_3))*τ\ndI_2/dt = (-2I_2 + 3I_3)*γ - I_2*γ + 2S_2*τ + (2I_1 - I_2)*ifelse((S_1 + 2S_2 + 3S_3) < 1.0e-12, 0, (S_1 + 4S_2 + 9S_3) / (S_1 + 2S_2 + 3S_3))*τ\ndI_3/dt = -4I_3*γ + 3S_3*τ + I_2*ifelse((S_1 + 2S_2 + 3S_3) < 1.0e-12, 0, (S_1 + 4S_2 + 9S_3) / (S_1 + 2S_2 + 3S_3))*τ\n```\n:::\n:::\n\n\n\nThe `ifelse` guards the ratios where their denominators vanish. The numeric right-hand side\nagrees with the symbolic one:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(; max_gap_numeric_vs_symbolic = max_rhs_gap(nb, (du, u) -> rhs_sym!(du, u, (sc.params[:τ], sc.params[:γ]), 0.0)))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(max_gap_numeric_vs_symbolic = 6.938893903907228e-18,)\n```\n:::\n:::\n\n\n\n## Conservation laws\n\nThe node count is conserved, Σ_y([S_y] + [I_y]) = 1. Every SI edge is counted once from its S\nend and once from its I end, so Σ_y y[S_y] = Σ_y (k − y)[I_y] should hold as well. The closure\nmust preserve this. Along the solution on the scenario grid:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsol = solve_neighbourhood(nb; saveat = sc.tgrid)\nS(y) = [u[nb.index[(:S, y)]] for u in sol.u]\nI(y) = [u[nb.index[(:I, y)]] for u in sol.u]\nnodes  = sum(S(y) .+ I(y) for y in 0:k)\nSI_S   = sum(y .* S(y) for y in 0:k)\nSI_I   = sum((k - y) .* I(y) for y in 0:k)\n(; max_node_defect = maximum(abs.(nodes .- 1)), max_SI_defect = maximum(abs.(SI_S .- SI_I)))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(max_node_defect = 1.1102230246251565e-15, max_SI_defect = 4.4797499043625066e-14)\n```\n:::\n:::\n\n\n\n## Against simulation\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncnb = ModelCurves(sc.tgrid, Dict(:I => neighbourhood_compartment(nb, sol, :I), :S => neighbourhood_compartment(nb, sol, :S));\n                  label = \"neighbourhood n = 2\", representation = :neighbourhood)\npw  = node_based(model, sc.network)                  # population pairwise, Bernoulli closure K = (k − 1)/k\ncpw = model_curves(pw, solve_epidemic(pw, sc); t = sc.tgrid, label = \"pairwise\")\nref = scenario_summary(sc)\ntab = compare(ref, cnb, cpw; observables = [:I])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sis_reg3  (scenario 485d890e; conditioned mean of 200 runs)\n  curve                observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  neighbourhood n = 2  I            0.02525     10.75   0.00160     21.41       NaN  [     NaN,      NaN]  -0.00106     42.25     0.769\n  pairwise             I            0.14556      9.50   0.00160     93.69  14.70400  [14.70400, 14.70400]  -0.00023      2.00     0.153\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndescribe_reference(ref);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNetworkOutbreaks reference :sis_reg3 (hash 485d890e): N = 10000 nodes, 200 runs on a fresh graph per run, algorithm :next_reaction; conditioning: surviving runs only (prevalence at t_end > 0); 200 of 200 runs kept (surviving runs), P(survival) = 1.000 (95% CI 0.981–1.000); no time alignment.\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndistinct_styles!(comparisonplot(ref, cnb, cpw; observables = [:I]))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Neighbourhood model (n = 2) and pairwise model against the committed NetworkOutbreaks ensemble of `:sis_reg3`, conditioned on survival (spread band q2.5–q97.5 of the runs; residual panel: mean band ±1.96 SE).](index_files/figure-commonmark/cell-9-output-1.svg){}\n:::\n:::\n\n\n\nThe neighbourhood model does not track cumulative incidence (ΔR∞ is NaN). The pairwise row's\nΔR∞ is its `:cumulative` at t = 80, which counts reinfections, minus the simulated fraction of\nnodes ever infected, so it is not a final-size error (page N09 explains this):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfs = ref.final_size[ref.major]\n(; pairwise_cumulative_80 = cpw[:cumulative][end], mean_fraction_ever_infected = sum(fs) / length(fs),\n   ΔR∞_pairwise = tab[cpw.label, :I].ΔR∞)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(pairwise_cumulative_80 = 15.704003220388449, mean_fraction_ever_infected = 1.0, ΔR∞_pairwise = 14.704003220388449)\n```\n:::\n:::\n\n\n\nThe peak columns are not meaningful on an endemic plateau either. The largest gap and the endemic\nlevel:\n\n``` {.julia .cell-code}\nst = ref.cond[:I]\nmd_table([\"model\", \"variables\", \"D∞(I)\", \"t at D∞\", \"z∞\", \"I(80)\", \"I(80) − NO\"],\n         [(cnb.label, length(nb.var_names), tab[cnb.label, :I].D∞, tab[cnb.label, :I].t_D∞, tab[cnb.label, :I].z∞,\n           cnb[:I][end], cnb[:I][end] - st.mean[end]),\n          (cpw.label, length(pw.singles) + length(pw.pairs), tab[cpw.label, :I].D∞, tab[cpw.label, :I].t_D∞,\n           tab[cpw.label, :I].z∞, cpw[:I][end], cpw[:I][end] - st.mean[end]),\n          (\"NetworkOutbreaks (mean ± SE)\", \"–\", NaN, NaN, NaN, st.mean[end], st.se[end])])\n```\n| model | variables | D∞(I) | t at D∞ | z∞ | I(80) | I(80) − NO |\n|---|---:|---:|---:|---:|---:|---:|\n| neighbourhood n = 2 | 8 | 0.02525 | 10.75 | 21.41 | 0.8173 | 0.0002934 |\n| pairwise | 5 | 0.1456 | 9.5 | 93.69 | 0.8182 | 0.001126 |\n| NetworkOutbreaks (mean ± SE) | – | NaN | NaN | NaN | 0.8171 | 0.0003 |\n\n\n\n\n\n\n\nWith 8 variables the neighbourhood model reduces the largest\nprevalence gap of the pairwise model from 0\\.1456 to\n0\\.02525. Both approach the simulated endemic level: the endemic gaps\nare 0\\.0002934 and 0\\.001126,\nagainst a standard error of 0\\.0003. The model's own output also includes the\ndistribution of the number of infected neighbours. For example, at t = 80 a susceptible node\nhas on average 2\\.237 infected neighbours:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nbar(0:k, [S(y)[end] for y in 0:k]; bar_width = 0.35, label = \"S_y\", xlabel = \"infected neighbours y\",\n    ylabel = \"fraction of nodes\", title = \"Neighbourhood model at t = 80\")\nbar!((0:k) .+ 0.35, [I(y)[end] for y in 0:k]; bar_width = 0.35, label = \"I_y\")\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![The neighbourhood distribution at t = 80: the fraction of all nodes in [S_y] and [I_y].](index_files/figure-commonmark/cell-13-output-1.svg){}\n:::\n:::\n\n\n\nThe neighbourhood distribution is a prediction of the model only. The committed summary does not\nstore it, so it is not compared with the simulation here.\n\nNo Lean statement is involved on this page. Page [N12](../N12_sis_comparison/index.qmd) compares\nevery SIS approximation.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-commonmark"
    ],
    "filters": [],
    "includes": {}
  }
}