{
  "hash": "1bbbeec8848cebc4ade980d6bc3ff3e4",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"All SIS approximations against simulation\"\nsubtitle: \"NodeBasedModels.jl vignette N12: pairwise, reinfection-counting, motif and neighbourhood models of SIS on a 3-regular network against one NetworkOutbreaks ensemble\"\n---\n\n## What this page shows\n\nThe edge-based model stops at SIS (page E13): an arrow back into the susceptible class is outside\nT_EB. NodeBasedModels has four families of deterministic approximations for SIS, introduced on\nthe previous pages:\n\n- the population pairwise model with the Bernoulli closure (page N09);\n- the pairwise model with reinfection counting, capped at L (page N09);\n- the motif closures of order m = 2, 3, 4 (page N10);\n- the neighbourhood model with n = 2 (page N11).\n\nThis page compares all of them with the one committed NetworkOutbreaks ensemble of `:sis_reg3`.\nIt gives the transient and the endpoint in two tables, both computed from the summary. The\nmirrored EdgeBasedModels page E13 shows the same comparison for the pairwise, motif and\nneighbourhood models.\n\n## The shared first cell\n\nThis cell is the same as the first cell of EdgeBasedModels' page E13, apart from the back-end\nlines. On the EBM side, the back end refuses the model. Here it builds the pairwise model twice.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nrequire_summaries([:sis_reg3])                           # back end\nusing Statistics\nusing NetworkEpiCore, NetworkOutbreaks, Catalyst, Plots\nsis = @reaction_network sis begin\n    @parameters τ γ\n    τ, S + I --> 2I        # contact: per-contact (per-edge) rate τ\n    γ, I --> S             # recovery back into the susceptible class (type resus)\nend\nmodel = contact_model(sis)          # prints the typing report: T_net, not T_EB\nsc    = scenario(:sis_reg3)         # 3-regular, τ = 1/2, γ = 1/4, 1% seeds in I, t ∈ [0, 80]\n@assert isequivalent(model, sc.model)\nref   = scenario_summary(sc)        # committed NetworkOutbreaks ensemble, conditioned on survival\n# --- NBM vignette ---------------------------------------------------------------\nusing NodeBasedModels\nsys  = node_based(model, sc.network)                       # low level: pairwise, Bernoulli closure\nsysF = generate_pairwise(sis_model(), sc.network, default_closure(sc.network); cumulative = true)  # factory\n@assert vector_fields_equal(symbolic_ode(sys), symbolic_ode(sysF))\nmodel\n```\n\n::: {#shared-cell .cell-output .cell-output-display execution_count=1}\n```\nContactModel :sis  (source: Catalyst.ReactionSystem; method: stoichiometry; rates: PerContact)\n  species       S (Sus)   I\n  contacts      [1] S + I → I + I    τ    contact    infector I, entry I\n  transitions   [2] I → S            γ    resus\n  typing        T_net  ⇒  edge_based ✗  s_anchored ✗  pairwise ✓  individual ✓  pair ✓  stochastic ✓  mass_action ✓\n  violations    `γ, I --> S` (type resus: node → sus) produces the susceptible species S.\n  assumptions   Sus inferred as recipients \\ contact products = {S}\n```\n:::\n:::\n\n\n\nThe scenario and the reference:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\na = anchors(sc);\ndescribe_reference(ref);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n:sis_reg3: γ = 0.25, τ = 0.5; seeds I 0.01; t = 0:0.25:80; edge-based R₀ not defined (model outside T_EB); pairwise threshold τ_c = 0.125, τ/τ_c = 4 (differs from the canonical anchors: no edge-based R₀, τ ≠ 1/6)\nNetworkOutbreaks reference :sis_reg3 (hash 485d890e): N = 10000 nodes, 200 runs on a fresh graph per run, algorithm :next_reaction; conditioning: surviving runs only (prevalence at t_end > 0); 200 of 200 runs kept (surviving runs), P(survival) = 1.000 (95% CI 0.981–1.000); no time alignment.\n```\n:::\n:::\n\n\n\nThe scenario lists the back ends it expects to accept SIS, each with its verdict. None of them\nis exact. The error of each is reported here, not asserted:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsort(collect(sc.backends); by = first)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n7-element Vector{Pair{Symbol, Symbol}}:\n         :edge_based => :inadmissible\n              :motif => :approximate\n      :neighbourhood => :approximate\n :pairwise_bernoulli => :approximate\n     :pairwise_const => :approximate\n        :pgf_closure => :inadmissible\n        :reinfection => :approximate\n```\n:::\n:::\n\n\n\n## Every approximation on the scenario grid\n\nEvery model starts from the scenario's 1% infected at random. The reinfection-counting models\nseed the count-one class, and they are integrated with Tsit5 (page N09 shows why). The motif and neighbourhood systems are numeric ODEs with their own\nsolvers, and their prevalence is wrapped as `ModelCurves` on the scenario grid.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing OrdinaryDiffEqDefault: Tsit5\nρ = last(only(sc.initial.fractions))\ncpw = model_curves(sys, solve_epidemic(sys, sc); t = sc.tgrid, label = \"pairwise\")\nfunction reinfection_curves(L)\n    m = node_based(with_reinfection_counting(model, L), sc.network)\n    sol = solve_epidemic(m, sc; initial = SeedFraction(:I_1 => ρ), solver = Tsit5())   # see page N09\n    tot = reinfection_totals(m, sol)\n    ModelCurves(sc.tgrid, Dict(:I => tot[:I], :cumulative => model_curves(m, sol; t = sc.tgrid)[:cumulative]);\n                label = \"reinfection L = $(L)\", representation = :reinfection,\n                metadata = Dict(:variables => length(m.singles) + length(m.pairs)))\nend\nfunction motif_curves(m)\n    s = node_based(model, sc.network; level = :motif, closure = MotifClosure(3, m), p = sc.params,\n                   initial = sc.initial, tspan = sc.tspan)\n    ModelCurves(sc.tgrid, Dict(:I => compartment(s, solve_motif(s; saveat = sc.tgrid), :I));\n                label = \"motif m = $(m)\", representation = :motif,\n                metadata = Dict(:variables => length(s.variables)))\nend\nnb  = node_based(model, sc.network; level = :neighbourhood, n = 2, p = sc.params, initial = sc.initial,\n                 tspan = sc.tspan)\ncnb = ModelCurves(sc.tgrid, Dict(:I => neighbourhood_compartment(nb, solve_neighbourhood(nb; saveat = sc.tgrid), :I));\n                  label = \"neighbourhood n = 2\", representation = :neighbourhood,\n                  metadata = Dict(:variables => length(nb.var_names)))\napprox = [cpw, reinfection_curves(1), reinfection_curves(2), motif_curves(2), motif_curves(3), motif_curves(4), cnb]\nnvars = Dict(c.label => get(c.metadata, :variables, length(sys.singles) + length(sys.pairs)) for c in approx)\ntab = compare(ref, approx; observables = [:I])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sis_reg3  (scenario 485d890e; conditioned mean of 200 runs)\n  curve                observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  pairwise             I            0.14556      9.50   0.00160     93.69  14.70400  [14.70400, 14.70400]  -0.00023      2.00     0.153\n  reinfection L = 1    I            0.00289     14.25   0.00160      6.71  14.48108  [14.48108, 14.48108]  -0.00023      8.75     0.287\n  reinfection L = 2    I            0.00382      9.75   0.00160      5.33  14.47579  [14.47579, 14.47579]  -0.00023     41.00     0.243\n  motif m = 2          I            0.14556      9.50   0.00160     93.69       NaN  [     NaN,      NaN]  -0.00023      4.00     0.153\n  motif m = 3          I            0.06009      9.75   0.00160     39.65       NaN  [     NaN,      NaN]  -0.00025    -17.50     0.202\n  motif m = 4          I            0.00888     10.75   0.00160     11.27       NaN  [     NaN,      NaN]  -0.00016    -15.50     0.688\n  neighbourhood n = 2  I            0.02525     10.75   0.00160     21.41       NaN  [     NaN,      NaN]  -0.00106     42.25     0.769\n```\n:::\n:::\n\n\n\n::: {.cell fig-height='6' execution_count=1}\n``` {.julia .cell-code}\ndistinct_styles!(comparisonplot(ref, approx...; observables = [:I]))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Every SIS approximation against the committed NetworkOutbreaks ensemble of `:sis_reg3`, conditioned on survival (spread band q2.5–q97.5 of the runs; residual panel: mean band ±1.96 SE).](index_files/figure-pdf/cell-6-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\nThe ΔR∞ column of `compare` is not meaningful for SIS. It subtracts the simulated fraction of\nnodes ever infected from the model's cumulative incidence at t = 80, which counts reinfections, and\nonly the pairwise-type curves carry cumulative incidence at all (page N09 prints both numbers). The peak columns are not\nmeaningful on an endemic plateau either. The two tables below are the comparison.\n\n## The transient\n\nThe transient is summarised by the largest prevalence gap D∞ and its time, by the standardised\ngap z∞, by the fraction of the grid on which the curve lies within the mean band (coverage), and\nby the time t½ at which prevalence first reaches half of its final simulated value:\n\n``` {.julia .cell-code}\nst = ref.cond[:I]\nhalf = st.mean[end] / 2\nt_half(x) = sc.tgrid[findfirst(≥(half), x)]\ntrows = Any[(c.label, nvars[c.label], tab[c.label, :I].D∞, tab[c.label, :I].t_D∞, tab[c.label, :I].z∞,\n          tab[c.label, :I].coverage, t_half(c[:I]), t_half(c[:I]) - t_half(st.mean)) for c in approx]\npush!(trows, (\"NetworkOutbreaks (mean)\", \"–\", 0.0, NaN, NaN, NaN, t_half(st.mean), 0.0))\nmd_table([\"model\", \"variables\", \"D∞(I)\", \"t at D∞\", \"z∞\", \"coverage\", \"t½\", \"t½ − NO\"], trows)\n```\n| model | variables | D∞(I) | t at D∞ | z∞ | coverage | t½ | t½ − NO |\n|---|---:|---:|---:|---:|---:|---:|---:|\n| pairwise | 5 | 0.1456 | 9.5 | 93.69 | 0.1526 | 7.5 | -1.25 |\n| reinfection L = 1 | 9 | 0.002891 | 14.25 | 6.713 | 0.2866 | 8.75 | 0 |\n| reinfection L = 2 | 20 | 0.003824 | 9.75 | 5.333 | 0.243 | 8.75 | 0 |\n| motif m = 2 | 5 | 0.1456 | 9.5 | 93.69 | 0.1526 | 7.5 | -1.25 |\n| motif m = 3 | 15 | 0.06009 | 9.75 | 39.65 | 0.2025 | 8.25 | -0.5 |\n| motif m = 4 | 65 | 0.008878 | 10.75 | 11.27 | 0.6885 | 8.5 | -0.25 |\n| neighbourhood n = 2 | 8 | 0.02525 | 10.75 | 21.41 | 0.7695 | 8.5 | -0.25 |\n| NetworkOutbreaks (mean) | – | 0 | NaN | NaN | NaN | 8.75 | 0 |\n\n\n\n\n## The endpoint\n\nThe endpoint is summarised by the prevalence at t = 80 and its mean over the last 20 time units,\neach against the simulated mean with its standard error. For the models that carry it, it also\nincludes the mean number of infections per node:\n\n``` {.julia .cell-code}\nlate = findall(≥(last(sc.tgrid) - 20), sc.tgrid)\ncum = ref.cond[:cumulative]\nerows = Any[]\nfor c in approx\n    cumv = haskey(c.values, :cumulative) ? c[:cumulative][end] : NaN\n    push!(erows, (c.label, c[:I][end], c[:I][end] - st.mean[end], mean(c[:I][late]),\n                  mean(c[:I][late]) - mean(st.mean[late]), cumv, cumv - cum.mean[end]))\nend\npush!(erows, (\"NetworkOutbreaks (mean)\", st.mean[end], st.se[end], mean(st.mean[late]), NaN, cum.mean[end], cum.se[end]))\nmd_table([\"model\", \"I(80)\", \"I(80) − NO\", \"mean I, t ∈ [60, 80]\", \"difference\", \"cumulative(80)\", \"difference\"], erows)\n```\n| model | I(80) | I(80) − NO | mean I, t ∈ [60, 80] | difference | cumulative(80) | difference |\n|---|---:|---:|---:|---:|---:|---:|\n| pairwise | 0.8182 | 0.001126 | 0.8182 | 0.001057 | 15.7 | 0.2381 |\n| reinfection L = 1 | 0.8182 | 0.001126 | 0.8182 | 0.001057 | 15.48 | 0.01513 |\n| reinfection L = 2 | 0.8182 | 0.001126 | 0.8182 | 0.001057 | 15.48 | 0.00984 |\n| motif m = 2 | 0.8182 | 0.001126 | 0.8182 | 0.001057 | NaN | NaN |\n| motif m = 3 | 0.8163 | -0.0007423 | 0.8163 | -0.0008111 | NaN | NaN |\n| motif m = 4 | 0.8174 | 0.0003262 | 0.8174 | 0.0002625 | NaN | NaN |\n| neighbourhood n = 2 | 0.8173 | 0.0002934 | 0.8173 | 0.0002246 | NaN | NaN |\n| NetworkOutbreaks (mean) | 0.8171 | 0.0003 | 0.8171 | NaN | 15.47 | 0.003598 |\n\n\n\n\nThe last row gives the simulated values, with the standard error of the mean in the difference\ncolumns where it is defined.\n\n\n\n\nAt t = 80 every approximation is within 0\\.001126 of the simulated endemic prevalence\n0\\.8171, whose standard error is 0\\.0003. The endemic level is\ntherefore not what separates them. The transient does. Over the whole time course the closest\ncurve is reinfection L = 1 (D∞(I) = 0\\.002891), and the furthest is\npairwise (D∞(I) = 0\\.1456), together with the motif closure m = 2. The motif closure with m = 2 is Keeling's\npairwise closure: its curve differs from the pairwise one by at most 1\\.753e\\-09.\n\n## The take-off\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\np = plot(ref, :I; median = false, legend = :bottomright, xlabel = \"t\", ylabel = \"I (fraction of nodes)\",\n         title = \"SIS on a 3-regular network: take-off\")\nfor c in approx\n    plot!(p, c, :I)\nend\ndistinct_styles!(p)\nxlims!(p, 0, 30)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![The first 30 time units of the comparison (prevalence; band: spread q2.5–q97.5 of the surviving runs).](index_files/figure-pdf/cell-10-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\np2 = plot(; xscale = :log10, yscale = :log10, xlabel = \"number of variables\", ylabel = \"D∞(I)\",\n          legend = :outerright, title = \"Accuracy and size\", size = (820, 460),\n          left_margin = 5Plots.mm, bottom_margin = 6Plots.mm)\nshapes = [:circle, :rect, :diamond, :utriangle, :dtriangle, :star5, :hexagon]\nfor (i, c) in enumerate(approx)       # decreasing sizes and distinct shapes keep coinciding points visible\n    scatter!(p2, [nvars[c.label]], [tab[c.label, :I].D∞]; label = c.label, markershape = shapes[i],\n             markersize = 10 - i, markerstrokewidth = 1.5, markeralpha = 0.7)\nend\nhline!(p2, [maximum(st.se)]; linestyle = :dot, color = :gray, label = \"SE∞\")\np2\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Largest prevalence gap D∞(I) against the number of variables of each approximation (log scales); the dotted line is the largest standard error of the simulated mean. The pairwise and motif m = 2 points coincide, so they are drawn with different shapes and sizes.](index_files/figure-pdf/cell-11-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\nNone of these is exact. They are moment closures of an SIS process on a random 3-regular graph,\nand the simulation is the reference. No Lean statement is involved on this page.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-pdf"
    ],
    "filters": [],
    "includes": {}
  }
}