# compartments.jl — the compartmental model type of NodeBasedModels (owner: WP15)
#
# A `CompartmentalModel` is a set of compartments (S, I, R, E, …) with transitions between them.
# Each transition has a type:
#   - :infection   — needs contact with an infectious neighbour (the infectors in `via`);
#   - :spontaneous — happens at a constant per-capita rate (recovery, waning immunity, …).
#
# Since 0.2 the canonical model object is NetworkEpiCore's `ContactModel` (`sir_model()` and
# friends return one, and `node_based` takes any model that `contact_model` accepts). The
# `CompartmentalModel` is kept as the lowering target of the population pairwise builder and as
# a legacy input; `contact_model(::CompartmentalModel)` and `CompartmentalModel(::ContactModel)`
# (compat.jl) convert both ways. The 0.1 constructors (`node_sir_model`, `model_from_catalyst`)
# are in deprecated.jl.

"""
    Compartment(name; infectious=false)

A disease compartment. Set `infectious=true` for compartments that can
transmit infection (e.g., I in SIR).
"""
struct Compartment
    name::Symbol
    infectious::Bool
end

Compartment(name::Symbol; infectious::Bool = false) = Compartment(name, infectious)

"""
    TRANSITION_TYPES

The transition types of a [`Transition`](@ref): `:infection` (driven by contacts with the
infectors in `via`) and `:spontaneous` (a per-capita rate).
"""
const TRANSITION_TYPES = (:infection, :spontaneous)

"""
    Transition(from, to, rate, type; via = Symbol[])

A transition between compartments.

- `type = :infection` — `rate` is the per-contact (per-edge) transmission rate τ; the
  transition happens along edges to the infectious compartments in `via`, so a node in `from`
  with an infectious neighbour in `Z ∈ via` moves to `to` at rate τ per such edge.
- `type = :spontaneous` — `rate` is a per-capita rate (γ, σ, …); `via` must be empty.
- `via` — the infectors (catalysts) of an infection. **Empty means every infectious compartment
  of the model**, which is the NodeBasedModels 0.1 behaviour. Per-infector rates are two
  transitions with the same `from` and `to`: `Transition(:S, :I1, :τ1, :infection; via = [:I1])`
  and `Transition(:S, :I1, :τ2, :infection; via = [:I2])` give
  d[S]/dt = −τ1[S I1] − τ2[S I2] (verified issue B04).
- `rate` — a parameter name (`Symbol`), a non-negative number, an `Expr` over parameter names
  using `NetworkEpiCore.RATE_OPS` (with `t` for time), or a symbolic (Symbolics) expression,
  validated by the same rules as `NetworkEpiCore.NodeTransition`.
"""
struct Transition
    from::Symbol
    to::Symbol
    rate::Any
    type::Symbol
    via::Vector{Symbol}
    function Transition(from::Symbol, to::Symbol, rate, type::Symbol, via::AbstractVector{Symbol})
        where = "Transition($(repr(from)), $(repr(to)), …, $(repr(type)))"
        type in TRANSITION_TYPES || throw(ArgumentError(
            "$where: the type must be one of $(TRANSITION_TYPES); got $(repr(type))"))
        (type === :infection || isempty(via)) || throw(ArgumentError(
            "$where: only :infection transitions have infectors (`via`); got via = $(via)"))
        allunique(via) || throw(ArgumentError("$where: `via` lists a compartment twice: $(via)"))
        # The IR's rate rules (numbers ≥ 0, RATE_OPS expressions, no Julia functions).
        r = NodeTransition(from, to, rate).rate
        return new(from, to, r, type, collect(Symbol, via))
    end
end

Transition(from::Symbol, to::Symbol, rate, type::Symbol; via::AbstractVector{Symbol} = Symbol[]) =
    Transition(from, to, rate, type, via)

"""
    CompartmentalModel(compartments, transitions; name)

A compartmental epidemic model. Defines the disease dynamics independently
of network structure. The pairwise system is generated by combining this
with a `NetworkStructure` and a `ClosureMethod`.

Checks that every transition refers to known compartments, that the model has an infectious
compartment, and that the infectors (`via`) of every infection transition are infectious
compartments.

`susceptible_compartments` are the sources of the infection transitions, in order; the first
one is the **background** compartment that holds every unseeded node in the default initial
condition.

# Example
```julia
sir = CompartmentalModel(
    [Compartment(:S), Compartment(:I; infectious=true), Compartment(:R)],
    [Transition(:S, :I, :τ, :infection),
     Transition(:I, :R, :γ, :spontaneous)];
    name = :SIR
)
```

In NodeBasedModels 0.2 `sir_model()` returns a `NetworkEpiCore.ContactModel`;
`CompartmentalModel(sir_model())` is the model above (with name `:sir`).
"""
struct CompartmentalModel
    name::Symbol
    compartments::Vector{Compartment}
    transitions::Vector{Transition}
    compartment_names::Vector{Symbol}
    infectious_compartments::Vector{Symbol}
    susceptible_compartments::Vector{Symbol}

    function CompartmentalModel(
        compartments::Vector{Compartment},
        transitions::Vector{Transition};
        name::Symbol = :model
    )
        names = [c.name for c in compartments]
        infectious = [c.name for c in compartments if c.infectious]
        # Susceptible = compartments that can become infected
        sources = unique([t.from for t in transitions if t.type == :infection])
        susceptible = sources

        allunique(names) || throw(ArgumentError(
            "Compartment names must be unique; got $(names)"))
        length(infectious) > 0 || throw(ArgumentError(
            "Model must have at least one infectious compartment"))

        for t in transitions
            t.from ∈ names || throw(ArgumentError("Unknown compartment: $(t.from)"))
            t.to ∈ names || throw(ArgumentError("Unknown compartment: $(t.to)"))
            for z in t.via
                z ∈ infectious || throw(ArgumentError(
                    "transition $(t.from) → $(t.to): the infector $(z) in `via` is not an " *
                    "infectious compartment (infectious: $(join(infectious, ", ")))"))
            end
        end

        new(name, compartments, transitions, names, infectious, susceptible)
    end
end

# ─── Utilities ─────────────────────────────────────────────────────────────────

"""
    infectors(model::CompartmentalModel, tr::Transition) -> Vector{Symbol}

The infectious compartments whose contacts drive the infection transition `tr`: `tr.via`, or
every infectious compartment of `model` when `via` is empty (the 0.1 semantics).
"""
infectors(model::CompartmentalModel, tr::Transition) =
    isempty(tr.via) ? model.infectious_compartments : tr.via

"""Return all unique ordered pairs of compartment names."""
function all_pairs(model::CompartmentalModel)
    names = model.compartment_names
    pairs = Tuple{Symbol,Symbol}[]
    for a in names, b in names
        push!(pairs, (a, b))
    end
    return pairs
end

"""Return infection transitions."""
function infection_transitions(model::CompartmentalModel)
    filter(t -> t.type == :infection, model.transitions)
end

"""Return spontaneous transitions."""
function spontaneous_transitions(model::CompartmentalModel)
    filter(t -> t.type == :spontaneous, model.transitions)
end

"""
    _rate_parameter_names(rate) -> Vector{Symbol}

The parameter names of a transition rate (none for a number, the rate itself for a `Symbol`,
the leaves of an `Expr`, the variables of a symbolic rate), excluding time `t`.
"""
_rate_parameter_names(rate::Symbol) = rate === :t ? Symbol[] : [rate]
_rate_parameter_names(rate) = Symbol[_parameter_symbol(p) for p in rate_parameters(rate)]
_parameter_symbol(p::Symbol) = p
_parameter_symbol(p) = Symbol(Symbolics.getname(p))

"""
    _rate_symbolic(rate, params::AbstractDict{Symbol}, t)

The rate as a symbolic expression in the MTK parameters `params` (keyed by name) and the
independent variable `t`: a `Symbol` is looked up (so a legacy model builds exactly the 0.1
equations), a number is returned as is, and `Expr` and symbolic rates are evaluated by
`NetworkEpiCore.rate_value`, which substitutes by name.
"""
_rate_symbolic(rate::Symbol, params::AbstractDict, t) = rate === :t ? t : params[rate]
function _rate_symbolic(rate, params::AbstractDict, t)
    (rate isa Real && !(rate isa Symbolics.Num)) && return rate
    return rate_value(rate, params; t = t)
end
