# compartments.jl — Compartmental model definitions
#
# Users specify disease models as a set of compartments (S, I, R, E, etc.)
# with transitions between them. Each transition has a type:
#   - :infection  — requires contact with an infected compartment
#   - :spontaneous — happens at a constant rate (recovery, waning immunity, etc.)

"""
    Compartment(name; infectious=false)

A disease compartment. Set `infectious=true` for compartments that can
transmit infection (e.g., I in SIR).
"""
struct Compartment
    name::Symbol
    infectious::Bool
end

Compartment(name::Symbol; infectious::Bool = false) = Compartment(name, infectious)

"""
    Transition(from, to, rate, type)

A transition between compartments.

- `type = :infection` — rate is per-SI-edge transmission rate (τ)
- `type = :spontaneous` — rate is per-capita rate (γ, σ, etc.)
"""
struct Transition
    from::Symbol
    to::Symbol
    rate::Symbol          # parameter name
    type::Symbol          # :infection or :spontaneous
end

"""
    CompartmentalModel(compartments, transitions; name)

A compartmental epidemic model. Defines the disease dynamics independently
of network structure. The pairwise system is generated by combining this
with a `NetworkStructure` and a `ClosureMethod`.

# Example
```julia
sir = CompartmentalModel(
    [Compartment(:S), Compartment(:I; infectious=true), Compartment(:R)],
    [Transition(:S, :I, :τ, :infection),
     Transition(:I, :R, :γ, :spontaneous)];
    name = :SIR
)
```
"""
struct CompartmentalModel
    name::Symbol
    compartments::Vector{Compartment}
    transitions::Vector{Transition}
    compartment_names::Vector{Symbol}
    infectious_compartments::Vector{Symbol}
    susceptible_compartments::Vector{Symbol}

    function CompartmentalModel(
        compartments::Vector{Compartment},
        transitions::Vector{Transition};
        name::Symbol = :model
    )
        names = [c.name for c in compartments]
        infectious = [c.name for c in compartments if c.infectious]
        # Susceptible = compartments that can become infected
        targets = unique([t.to for t in transitions if t.type == :infection])
        sources = unique([t.from for t in transitions if t.type == :infection])
        susceptible = sources

        length(infectious) > 0 || throw(ArgumentError(
            "Model must have at least one infectious compartment"))

        for t in transitions
            t.from ∈ names || throw(ArgumentError("Unknown compartment: $(t.from)"))
            t.to ∈ names || throw(ArgumentError("Unknown compartment: $(t.to)"))
        end

        new(name, compartments, transitions, names, infectious, susceptible)
    end
end

# ─── Built-in models ──────────────────────────────────────────────────────────

"""
    sir_model(; τ=:τ, γ=:γ)

Standard SIR model: S →[τ] I →[γ] R
"""
function sir_model(; τ::Symbol = :τ, γ::Symbol = :γ)
    CompartmentalModel(
        [Compartment(:S), Compartment(:I; infectious=true), Compartment(:R)],
        [Transition(:S, :I, τ, :infection),
         Transition(:I, :R, γ, :spontaneous)];
        name = :SIR
    )
end

"""
    sis_model(; τ=:τ, γ=:γ)

SIS model: S →[τ] I →[γ] S (no immunity)
"""
function sis_model(; τ::Symbol = :τ, γ::Symbol = :γ)
    CompartmentalModel(
        [Compartment(:S), Compartment(:I; infectious=true)],
        [Transition(:S, :I, τ, :infection),
         Transition(:I, :S, γ, :spontaneous)];
        name = :SIS
    )
end

"""
    seir_model(; τ=:τ, σ=:σ, γ=:γ)

SEIR model: S →[τ] E →[σ] I →[γ] R
"""
function seir_model(; τ::Symbol = :τ, σ::Symbol = :σ, γ::Symbol = :γ)
    CompartmentalModel(
        [Compartment(:S), Compartment(:E), Compartment(:I; infectious=true),
         Compartment(:R)],
        [Transition(:S, :E, τ, :infection),
         Transition(:E, :I, σ, :spontaneous),
         Transition(:I, :R, γ, :spontaneous)];
        name = :SEIR
    )
end

"""
    sirs_model(; τ=:τ, γ=:γ, ε=:ε)

SIRS model: S →[τ] I →[γ] R →[ε] S (waning immunity)
"""
function sirs_model(; τ::Symbol = :τ, γ::Symbol = :γ, ε::Symbol = :ε)
    CompartmentalModel(
        [Compartment(:S), Compartment(:I; infectious=true), Compartment(:R)],
        [Transition(:S, :I, τ, :infection),
         Transition(:I, :R, γ, :spontaneous),
         Transition(:R, :S, ε, :spontaneous)];
        name = :SIRS
    )
end

"""
    model_from_catalyst(rn::Catalyst.ReactionSystem; infectious=[:I])

Convert a Catalyst ReactionSystem to a CompartmentalModel.
Reactions with two reactants where one is in `infectious` are treated as
infection transitions; all others are spontaneous.
"""
_species_symbol(spec) = Symbol(Symbolics.tosymbol(spec; escape=false))

function _stoichiometry_dict(species, stoich)
    counts = Dict{Symbol,Int}()
    for (spec, coeff) in zip(species, stoich)
        counts[_species_symbol(spec)] = get(counts, _species_symbol(spec), 0) + Int(coeff)
    end
    return counts
end

function model_from_catalyst(rn::Catalyst.ReactionSystem;
                              infectious::Vector{Symbol} = [:I])
    species_names = [_species_symbol(spec) for spec in Catalyst.species(rn)]
    compartments = [Compartment(s; infectious = s ∈ infectious) for s in species_names]

    transitions = Transition[]
    for rx in Catalyst.reactions(rn)
        substrate_counts = _stoichiometry_dict(rx.substrates, rx.substoich)
        net_counts = Dict(_species_symbol(spec) => Int(coeff) for (spec, coeff) in rx.netstoich)
        total_substrates = sum(values(substrate_counts))
        infectious_substrates = [s for s in keys(substrate_counts) if s ∈ infectious]

        from_candidates = [s for (s, coeff) in net_counts if coeff < 0]
        to_candidates = [s for (s, coeff) in net_counts if coeff > 0]
        length(from_candidates) == 1 || throw(ArgumentError(
            "Reaction $(rx) does not map cleanly to a single-source compartmental transition."))
        length(to_candidates) == 1 || throw(ArgumentError(
            "Reaction $(rx) does not map cleanly to a single-target compartmental transition."))

        is_infection = total_substrates > 1 && !isempty(infectious_substrates)
        from_comp = only(from_candidates)
        to_comp = only(to_candidates)
        rate_sym = Symbol(Symbolics.tosymbol(rx.rate; escape=false))

        push!(transitions, Transition(from_comp, to_comp, rate_sym,
                                       is_infection ? :infection : :spontaneous))
    end

    CompartmentalModel(compartments, transitions; name = Symbol(Catalyst.nameof(rn)))
end

# ─── Utilities ─────────────────────────────────────────────────────────────────

"""Return all unique ordered pairs of compartment names."""
function all_pairs(model::CompartmentalModel)
    names = model.compartment_names
    pairs = Tuple{Symbol,Symbol}[]
    for a in names, b in names
        push!(pairs, (a, b))
    end
    return pairs
end

"""Return infection transitions."""
function infection_transitions(model::CompartmentalModel)
    filter(t -> t.type == :infection, model.transitions)
end

"""Return spontaneous transitions."""
function spontaneous_transitions(model::CompartmentalModel)
    filter(t -> t.type == :spontaneous, model.transitions)
end
