{
  "hash": "dde709123156252bf3d7ca1aa884951c",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"Motif closures\"\nsubtitle: \"NodeBasedModels.jl vignette N10: SIS motif closures of order m = 2, 3, 4 on a 3-regular network against NetworkOutbreaks\"\n---\n\n## What this page shows\n\nThe pairwise model tracks nodes and edges and closes triples. A motif closure of order m\n[Keeling, House, Cooper and Pellis 2016, *PLoS Comput. Biol.* 12:e1005296, approximation 2; see\nalso @house2011] tracks every connected induced subgraph with up to m vertices, by the states\nof its vertices, and closes the (m + 1)-vertex quantities. On a k-regular network with k = 3 the\npackage implements m = 2 (Keeling's pairwise model), m = 3 (paths and triangles) and m = 4 (the\nsix connected four-vertex shapes). This page:\n\n1. builds the motif systems from the Catalyst SIS model of `:sis_reg3` and from the direct\n   constructor `motif_based_sis`, and checks that they are the same system;\n2. lists the variables of each order and checks the numeric right-hand sides against the\n   independent symbolic builder;\n3. checks that m = 2 is the pairwise model;\n4. compares m = 2, 3, 4 with the committed NetworkOutbreaks ensemble.\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nrequire_summaries([:sis_reg3])\n```\n:::\n\n\n\n## The motif systems, twice\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing Catalyst, StableRNGs\nsis = @reaction_network sis begin\n    @parameters τ γ\n    τ, S + I --> 2I        # contact: per-contact (per-edge) rate τ\n    γ, I --> S             # recovery back into the susceptible class\nend\nmodel = contact_model(sis)\nsc = scenario(:sis_reg3)            # 3-regular, τ = 1/2, γ = 1/4, 1% seeds in I, t ∈ [0, 80]\n@assert isequivalent(model, sc.model)\nρ = last(only(sc.initial.fractions))\nms = 2:4\nlow = Dict(m => node_based(model, sc.network; level = :motif, closure = MotifClosure(3, m),\n                           p = sc.params, initial = sc.initial, tspan = sc.tspan) for m in ms)    # low level\ndirect = Dict(m => motif_based_sis(; β = sc.params[:τ], γ = sc.params[:γ], k = 3, m, tspan = sc.tspan, ε = ρ)\n              for m in ms)                                                                   # direct constructor\n# a summary of the m = 3 system: its shapes and its variables, written shape[states]\n(; m = 3, shapes = [s.name for s in low[3].shapes], n_variables = length(low[3].variables),\n   variables = join((string(v.shape.name, \"[\", join(v.state, \" \"), \"]\") for v in low[3].variables), \", \"))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(m = 3, shapes = [:singleton, :P2, :P3, :C3], n_variables = 15, variables = \"singleton[I], singleton[S], P2[I I], P2[I S], P2[S S], P3[I I I], P3[I I S], P3[I S I], P3[I S S], P3[S I S], P3[S S S], C3[I I I], C3[I I S], C3[I S S], C3[S S S]\")\n```\n:::\n:::\n\n\n\n`motif_based_sis` names the per-contact rate β, the keyword name it had in version 0.1; it is the\nτ of the rest of the package. A motif system is a numeric ODE (`rhs!`, `u0`), not a ModelingToolkit system, so the\ntwo forms are compared by their initial conditions and by their right-hand sides at random\nstates:\n\n``` {.julia .cell-code}\nfunction max_rhs_gap(a, b, rhs_b = (du, u) -> b.rhs!(du, u, b.params, 0.0); n = 25, seed = 1)\n    rng = StableRNG(seed)\n    d1, d2 = similar(a.u0), similar(a.u0)\n    gap = 0.0\n    for _ in 1:n\n        u = a.u0 .* (0.2 .+ 1.6 .* rand(rng, length(a.u0))) .+ 1e-3 .* rand(rng, length(a.u0))\n        a.rhs!(d1, u, a.params, 0.0)\n        rhs_b(d2, u)\n        gap = max(gap, maximum(abs.(d1 .- d2)))\n    end\n    return gap\nend\nmd_table([\"m\", \"variables\", \"u0 equal\", \"max rhs gap at 25 random states\"],\n         [(m, length(low[m].variables), low[m].u0 == direct[m].u0, max_rhs_gap(low[m], direct[m])) for m in ms])\n```\n| m | variables | u0 equal | max rhs gap at 25 random states |\n|---:|---:|---:|---:|\n| 2 | 5 | true | 0 |\n| 3 | 15 | true | 0 |\n| 4 | 65 | true | 0 |\n\n\n\n\n## The variables\n\nA variable counts the induced copies of a shape H whose vertices are in a given state, up to the\nautomorphisms of H, as unordered embeddings. For the pair shape P₂ this gives E_SS, E_IS and\nE_II. The Keeling pairwise counts are [SS] = 2E_SS, [SI] = E_IS and [II] = 2E_II. On a\nlarge random 3-regular graph the default host counts are those of a tree, with no triangles or\nother cycles. Per node they are:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nk = 3\n(; edges = k / 2, P3 = binomial(k, 2), P4 = (k / 2) * (k - 1)^2, K13 = binomial(k, 3), C3 = 0)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(edges = 1.5, P3 = 3, P4 = 6.0, K13 = 1, C3 = 0)\n```\n:::\n:::\n\n\n\n``` {.julia .cell-code}\nrows = []\nfor m in ms\n    byshape = Dict{Symbol,Int}()\n    for v in low[m].variables\n        byshape[v.shape.name] = get(byshape, v.shape.name, 0) + 1\n    end\n    for sh in low[m].shapes\n        push!(rows, (m, string(sh.name), sh.n_nodes, length(sh.edges), length(sh.automorphisms),\n                     get(byshape, sh.name, 0)))\n    end\nend\nmd_table([\"m\", \"shape\", \"vertices\", \"edges\", \"order of Aut\", \"state classes\"], rows)\n```\n| m | shape | vertices | edges | order of Aut | state classes |\n|---:|---|---:|---:|---:|---:|\n| 2 | singleton | 1 | 0 | 1 | 2 |\n| 2 | P2 | 2 | 1 | 2 | 3 |\n| 3 | singleton | 1 | 0 | 1 | 2 |\n| 3 | P2 | 2 | 1 | 2 | 3 |\n| 3 | P3 | 3 | 2 | 2 | 6 |\n| 3 | C3 | 3 | 3 | 6 | 4 |\n| 4 | singleton | 1 | 0 | 1 | 2 |\n| 4 | P2 | 2 | 1 | 2 | 3 |\n| 4 | P3 | 3 | 2 | 2 | 6 |\n| 4 | C3 | 3 | 3 | 6 | 4 |\n| 4 | P4 | 4 | 3 | 2 | 10 |\n| 4 | K13 | 4 | 3 | 6 | 8 |\n| 4 | paw | 4 | 4 | 2 | 12 |\n| 4 | C4 | 4 | 4 | 8 | 6 |\n| 4 | K4me | 4 | 5 | 4 | 9 |\n| 4 | K4 | 4 | 6 | 24 | 5 |\n\n\n\n\nThe realised graphs of the ensemble are locally tree-like, as the defaults assume. The mean\nclustering coefficient of the 200 sampled graphs is\n0\\.00016.\n\nThe closure at order m replaces each (m + 1)-vertex quantity with a ratio of tracked ones. An S\nvertex i of a motif has n_ext(i) = k − deg_motif(i) neighbours outside the motif. For m = 3 the\nexpected number of infected ones is estimated from a single-vertex anchor,\n\n$$\nn_{\\mathrm{ext}}(i)\\,\\frac{L(\\sigma_i, I)}{k\\,\\langle \\sigma_i \\rangle},\n$$\n\nwhere L(σᵢ, I) is the labelled count of pairs (σᵢ, I) and ⟨σᵢ⟩ the number of nodes in state\nσᵢ. For m = 2 this is Keeling's factor (k − 1)/k. For m = 4 the external neighbour of a\nfour-vertex motif is closed through a three-vertex anchor that contains the infected vertex (a\nper-shape Kirkwood closure), and the P₃ and C₃ equations are the marginals of the four-vertex\nequations.\n\nThe numeric right-hand sides are checked against `build_motif_symbolic_rhs`, a symbolic builder\nthat assembles the equations from the shape and state-class enumeration and does not call the\nnumeric builders. At m = 4 it uses the same table of closure rules as the numeric code, so there\nit checks the assembly of the equations, not the choice of closure:\n\n``` {.julia .cell-code}\nfunction oracle_gap(m)\n    rhs_sym!, keys_sym, _ = build_motif_symbolic_rhs(MotifClosure(3, m))\n    order_ok = keys_sym == [(v.shape.name, v.state) for v in low[m].variables]\n    return (order_ok, max_rhs_gap(low[m], low[m], (du, u) -> rhs_sym!(du, u, (sc.params[:τ], sc.params[:γ]), 0.0)))\nend\nmd_table([\"m\", \"same variable order\", \"max abs(numeric − symbolic) at 25 random states\"],\n         [(m, oracle_gap(m)...) for m in ms])\n```\n| m | same variable order | max abs(numeric − symbolic) at 25 random states |\n|---:|---:|---:|\n| 2 | true | 2.776e-17 |\n| 3 | true | 2.22e-16 |\n| 4 | true | 4.441e-16 |\n\n\n\n\n## m = 2 is the pairwise model\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\npw  = node_based(model, sc.network)                  # population pairwise, Bernoulli closure K = (k − 1)/k\ncpw = model_curves(pw, solve_epidemic(pw, sc); t = sc.tgrid, label = \"pairwise\")\nfunction motif_curves(m)\n    s = low[m]\n    sol = solve_motif(s; saveat = sc.tgrid)\n    ModelCurves(sc.tgrid, Dict(:I => compartment(s, sol, :I), :S => compartment(s, sol, :S));\n                label = \"motif m = $(m)\", representation = :motif)\nend\ncms = [motif_curves(m) for m in ms]\n(; max_gap_I = maximum(abs.(cms[1][:I] .- cpw[:I])))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(max_gap_I = 1.7526654572108669e-9,)\n```\n:::\n:::\n\n\n\n## Against simulation\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nref = scenario_summary(sc)\ntab = compare(ref, cms; observables = [:I])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sis_reg3  (scenario 485d890e; conditioned mean of 200 runs)\n  curve        observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  motif m = 2  I            0.14556      9.50   0.00160     93.69       NaN  [     NaN,      NaN]  -0.00023      4.00     0.153\n  motif m = 3  I            0.06009      9.75   0.00160     39.65       NaN  [     NaN,      NaN]  -0.00025    -17.50     0.202\n  motif m = 4  I            0.00888     10.75   0.00160     11.27       NaN  [     NaN,      NaN]  -0.00016    -15.50     0.688\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndescribe_reference(ref);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNetworkOutbreaks reference :sis_reg3 (hash 485d890e): N = 10000 nodes, 200 runs on a fresh graph per run, algorithm :next_reaction; conditioning: surviving runs only (prevalence at t_end > 0); 200 of 200 runs kept (surviving runs), P(survival) = 1.000 (95% CI 0.981–1.000); no time alignment.\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndistinct_styles!(comparisonplot(ref, cms...; observables = [:I]))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Motif closures m = 2, 3, 4 against the committed NetworkOutbreaks ensemble of `:sis_reg3`, conditioned on survival (spread band q2.5–q97.5 of the runs; residual panel: mean band ±1.96 SE).](index_files/figure-commonmark/cell-11-output-1.svg){}\n:::\n:::\n\n\n\nThe motif systems do not track cumulative incidence, so ΔR∞ is not defined for them (NaN in the\ntable), and the peak columns are not meaningful on an endemic plateau. The largest gap and the\nendemic level:\n\n``` {.julia .cell-code}\nst = ref.cond[:I]\nmd_table([\"model\", \"variables\", \"D∞(I)\", \"t at D∞\", \"z∞\", \"I(80)\", \"I(80) − NO\"],\n         vcat([(c.label, length(low[m].variables), tab[c.label, :I].D∞, tab[c.label, :I].t_D∞, tab[c.label, :I].z∞,\n                c[:I][end], c[:I][end] - st.mean[end]) for (m, c) in zip(ms, cms)],\n              [(\"NetworkOutbreaks (mean ± SE)\", \"–\", NaN, NaN, NaN, st.mean[end], st.se[end])]))\n```\n| model | variables | D∞(I) | t at D∞ | z∞ | I(80) | I(80) − NO |\n|---|---:|---:|---:|---:|---:|---:|\n| motif m = 2 | 5 | 0.1456 | 9.5 | 93.69 | 0.8182 | 0.001126 |\n| motif m = 3 | 15 | 0.06009 | 9.75 | 39.65 | 0.8163 | -0.0007423 |\n| motif m = 4 | 65 | 0.008878 | 10.75 | 11.27 | 0.8174 | 0.0003262 |\n| NetworkOutbreaks (mean ± SE) | – | NaN | NaN | NaN | 0.8171 | 0.0003 |\n\n\n\n\n\n\n\nThe error of the transient decreases with the order: D∞(I) = 0\\.1456, 0\\.06009, 0\\.008878 for\nm = 2, 3, 4, at a cost of 5, 15, 65 variables.\nNone of the closures is exact on a random 3-regular graph, and at m = 4 the gap is still\nz∞ = 11\\.27 standard errors at its largest.\nThe error is largest during the take-off:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\np = plot(ref, :I; median = false, legend = :bottomright, xlabel = \"t\", ylabel = \"I (fraction of nodes)\",\n         title = \"Motif closures: take-off\")\nfor c in cms\n    plot!(p, c, :I)\nend\ndistinct_styles!(p)\nxlims!(p, 0, 30)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![The first 30 time units (prevalence; band: spread q2.5–q97.5 of the surviving runs).](index_files/figure-commonmark/cell-14-output-1.svg){}\n:::\n:::\n\n\n\nThe design of this page planned to show m = 4 as an open implementation issue, because an\nearlier order-4 builder gave a larger error than m = 3. With the current builder, whose right-hand\nside agrees with the symbolic lift above, the error decreases strictly with the order:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(; D∞ = Dict(zip(ms, D)), strictly_decreasing_in_m = all(diff(D) .< 0))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(D∞ = Dict(4 => 0.008877952628343344, 2 => 0.1455586067337321, 3 => 0.06009337362097189), strictly_decreasing_in_m = true)\n```\n:::\n:::\n\n\n\nNo Lean statement is involved on this page. Page [N11](../N11_neighbourhood/index.qmd) gives\nthe neighbourhood model, and page [N12](../N12_sis_comparison/index.qmd) compares every SIS\napproximation.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-commonmark"
    ],
    "filters": [],
    "includes": {}
  }
}